spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update  # Para producción, actualiza sin borrar datos
    defer-datasource-initialization: true
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  server:
    port: ${PORT:8080}

  sql:
    init:
      mode: never  # O 'never' si no quieres data.sql en producción
      encoding: UTF-8

  h2:
    console:
      enabled: false  # Deshabilitar H2 en producción